name: CI Pipeline

on:
  push:
    branches:
      - org
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run Tests
      run: mvn test -Dspring.profiles.active=test -Dspring.test.context.configuration=com.ot.moto.MotoApplication

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Install SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Application
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
        "cd ${{ secrets.WORK_DIR }} && \
         sudo chown -R jdlearn:jdlearn /home/MotopointBackend && \
         sudo git stash && \
         sudo git checkout ${{ secrets.MAIN_BRANCH }} && \
         sudo git pull && \
         sudo mvn install && \
         sudo systemctl restart backend.service && \
         exit"
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}

    - name: Cleanup
      run: rm -rf ~/.ssh
